name: Build and deploy
on:
  pull_request:
    types:
      - opened
      - closed
      - synchronize

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    container:
      image: adoptopenjdk/openjdk13:alpine-slim
    steps:
      - name: Run tests
        run: |
          mvn test
